### PR TITLE
Typescript migration

### PR DESCRIPTION
**Pull request by thisis-Shitanshu**
### Why?

Migrating the source code to TypeScript.
Issue #8 

### What is being changed?
- The basic setup has been implemented. `tsconfig` is at its place and I have added grunt to perform 3 tasks.
  - When starting compiling; automatically clean the previous build.
  - Run build using `tsconfig` and compile all the *.ts to *.js
  - Copy all the *.md files in actions from the src to the build.
- I have changed the test script name to `test:afterBuild`, specifying to run only after build.

- The progress so far:
  - [x] One PR to setup the infrastructure to handle the source and tests as TypeScript, rename the file extensions to *.ts, and begin building the output.
  - [ ] One PR for each bot action that updates the contents of each *.ts file and adds all the necessary type declarations.
  - [x] One PR to update the non-action-specific contents of the tests/ directory.
  - [x] One PR to update the contents of the helpers/ directory.
  - [x] One PR to update actions/index.js.
  - [x] One PR to update index.js
  - [x] Bonus: One or two PRs to update the contents of the scripts/ directory 🤷‍♂
---

### CODE REVIEW

**Comment by crichID** [comment]
@thisis-Shitanshu thank you for taking these first steps in migrating the components over to Typescript. I'll let @JamesMGreene do the official review but just wanted to stop by with :sparkles: and thanks!

**Comment by thisis-Shitanshu** [comment]
@crichID you're awesome! 🥇 thanks so much for stopping by, it's very motivating.

**Comment by heiskr** [comment]
Hi @thisis-Shitanshu , is there a way to break up this pull request into several smaller ones? I'm not familiar with a Typescript migration process; but I think fixing the conflicts now given the size of the PR is going to take a long time.

**Comment by thisis-Shitanshu** [comment]
Hi @heiskr, I totally agree with you. There're a lot of conflicting files here. I apologize, I made this PR too large and there're still more "action" files to come.
Surely, I can do individual sub-PRs for this, one every weekend over the course of starting next month. I will refer you and this PR so that we can keep track of the progress accordingly:
- [ ] PR to set up the infrastructure to handle the source and tests as TypeScript, rename the file extensions to *.ts starting the contents of the scripts/ directory.
- [ ] PR to update index.js & actions/index.js. and to update the non-action-specific contents of the tests/ directory.
- [ ] PR to update the contents of the helpers/ directory.
- [ ] PR for each bot action that updates the contents of each *.ts file and adds all the necessary type declarations.

This will be more systematic and will you ample time over the week to go through the code review and accept the PR. Sounds Good?

**Comment by heiskr** [comment]
These PRs are a year out of date, so I'm closing. Feel free to make a new branch

**Pull request closed without merging**
